In [70]:
import numpy as np
import time

arr_nonvectorized = np.random.rand(1000, 1000)
arr_vectorized = np.array(arr_nonvectorized) 


start_nv = time.time()
for i in range(1000):  
    for j in range(1000):  
        arr_nonvectorized[i, j] *= 3  

end_nv = time.time()
print("Time taken in non-vectorized approach:", 1000*(end_nv-start_nv), "ms")

start_v = time.time()
arr_vectorized*=3
end_v = time.time()
print("Time taken in vectorized approach:", 1000*(end_v-start_v), "ms")
print(np.allclose(arr_nonvectorized, arr_vectorized))

Time taken in non-vectorized approach: 136.50202751159668 ms
Time taken in vectorized approach: 0.2570152282714844 ms
True


In [71]:
import numpy as np
A = np.random.rand(500, 500)
B = np.random.rand(500, 500)

C_nonvectorized = np.zeros((500, 500))

start_nv = time.time()
for i in range(500):
   for j in range(500):
     C_nonvectorized[i,j]=A[i,j]*B[i,j]
end_nv = time.time()
print("Time taken in non-vectorized approach:", 1000 * (end_nv - start_nv), "ms")

C_vectorized = np.zeros((500,500))
start_v = time.time()
C_vectorized=A*B
end_v = time.time()
print("Time taken in vectorized approach:", 1000 * (end_v - start_v), "ms")


print(np.allclose(C_nonvectorized, C_vectorized))

Time taken in non-vectorized approach: 60.82797050476074 ms
Time taken in vectorized approach: 0.8311271667480469 ms
True


In [87]:
import numpy as np

points = np.random.rand(5, 2) * 10
print("2D Points:\n", points)

points_diff=points[:,np.newaxis,]-points 
distance_matrix = np.linalg.norm(points_diff, axis=2)
print(distance_matrix)


2D Points:
 [[8.11252588 4.00666852]
 [8.53033904 1.42409116]
 [1.23318506 1.39721183]
 [8.3820358  2.03368969]
 [9.00238629 0.97874712]]
[[0.         2.61615628 7.35762151 1.99130136 3.15597205]
 [2.61615628 0.         7.29720349 0.62737884 0.64896835]
 [7.35762151 7.29720349 0.         7.17712832 7.78046274]
 [1.99130136 0.62737884 7.17712832 0.         1.22382129]
 [3.15597205 0.64896835 7.78046274 1.22382129 0.        ]]
